{{ if .Values.dind.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: "{{ .Values.dind.image.repository }}:{{ .Values.dind.image.tag }}"
        imagePullPolicy: "{{ .Values.dind.image.pullPolicy }}"
        tty: true
        securityContext:
          privileged: true
        ports:
        - name: dind-con-port
          containerPort: {{ .Values.dind.service.port }}
          hostPort: {{ .Values.dind.service.port }}
          protocol: TCP
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        env:
        - name: DOCKER_TLS_VERIFY
          value: "0"
        - name: DOCKER_HOST
          value: "tcp://localhost:{{ .Values.dind.service.port }}"
      volumes:
      - name: dind-storage
        persistentVolumeClaim:
          claimName: dind-storage
{{ end }}