{{ if .Values.dind.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind-daemon
        image: "{{ .Values.dind.image.repository }}:{{ .Values.dind.image.tag }}"
        imagePullPolicy: "{{ .Values.dind.image.pullPolicy }}"
        securityContext:
          privileged: true
        # ports:
        # - name: dind-con-port
        #   containerPort: {{ .Values.dind.service.port }}
        #   hostPort: 2375
        #   protocol: TCP
        command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
        volumeMounts:
        - name: docker-tls-certdir
          mountPath: /certs
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: docker-tls-certdir
        emptyDir: {}
      - name: dind-storage
        persistentVolumeClaim:
          claimName: dind-storage
      
{{ end }}