backstage:
  ingress:
    enabled: true
    className: traefik
    host: backstage.mycluster.localhost
  clusterDomain: backstage.mycluster.localhost
  serviceAccount:
    create: true
  backstage:
    revisionHistoryLimit: 0
    extraEnvVars:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-db-secrets
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-db-secrets
          key: password

    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: GITHUB_TOKEN
    
    - name: AUTH_GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: AUTH_GITHUB_CLIENT_ID
    
    - name: AUTH_GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: AUTH_GITHUB_CLIENT_SECRET

    appConfig:
      app:
        title: My Backstage example
        baseUrl: http://backstage.mycluster.localhost
        experimental:
          packages: all # ✨

      backend:
        baseUrl: http://backstage.mycluster.localhost
        listen:
          port: 7007
        database:
          client: pg
          connection:
            host: postgres
            port: 5432
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}          

      organization:
        name: Squirrel-Soft
