backstage:
  ingress:
    enabled: true
    className: traefik
    host: backstage.mycluster.localhost
  clusterDomain: backstage.mycluster.localhost
  serviceAccount:
    create: true
  backstage:
    image:
      registry: ghcr.io
      repository: medoni/2025-backstage/backstage
      tag: latest
      pullPolicy: Always
    revisionHistoryLimit: 0
    extraEnvVars:
    - name: APP_BASEURL
      value: http://backstage.mycluster.localhost
    - name: BACKEND_BASEURL
      value: http://backstage.mycluster.localhost
    - name: BACKEND_DATABASE_PG_HOST
      value: postgres
    - name: BACKEND_DATABASE_PG_PORT
      value: "5432"
    - name: BACKEND_DATABASE_PG_USER
      valueFrom:
        secretKeyRef:
          name: postgres-db-secrets
          key: username
    - name: BACKEND_DATABASE_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-db-secrets
          key: password

    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: GITHUB_TOKEN
    
    - name: AUTH_GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: AUTH_GITHUB_CLIENT_ID
    
    - name: AUTH_GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: backstage-secrets
          key: AUTH_GITHUB_CLIENT_SECRET
    
    extraVolumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
    extraVolumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    