name: Build and publish backstage image

on:
  workflow_dispatch:

jobs:
  build-and-publish-docker-image:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.13
    
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --immutable
        dir: src/backstage/n12-backstage
    
    - name: Run Yarn build:backend
      uses: borales/actions-yarn@v4
      with:
        cmd: build:backend
        dir: src/backstage/n12-backstage
    
    - name: Run Yarn tsc
      uses: borales/actions-yarn@v4
      with:
        cmd: yarn tsc
        dir: src/backstage/n12-backstage

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install minver CLI
      run: dotnet tool install --tool-path ./minver minver-cli --version 4.3.0
    
    - name: Calculate version using minver CLI
      id: version
      run: |
          echo "version=$(./minver/minver --default-pre-release-identifiers alpha --tag-prefix v)" >> "$GITHUB_ENV"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}/backstage:${{ env.version }} \
          -f src/backstage/n12-backstage/packages/backend/Dockerfile \
          src/backstage/n12-backstage

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/backstage:${{ env.version }}
